[models]
#funktioniert
meta-llama-3.1-8b-instruct=""
Llama-3.3-70B-Instruct=""
Llama-3.1-SauerkrautLM-70b-Instruct=""

codestral-22b=""

mistral-large-instruct=""

Qwen2.5-72B-Instruct=""
Qwen2.5-Coder-32B-Instruct=""
Qwen2.5-VL-72B-Instruct=""

internvl2.5-8b=""

deepseek-r1-distill-llama-70b = ""
DeepSeek-R1=""

#embedding only -> nicht zu gebrauchen
#e5-mistral-7b-instruct=e5-mistral-7b-instruct

[run specs]
conv_length = 4
patient_length = 1
medic_length = 1